version: "3"

services: 
  mongo:
      ports:
      - "27017:27017"
      volumes:
        - ./mongo/initdb:/docker-entrypoint-initdb.d  # 启动初期数据绑定位置
        - ./mongo/datadb:/data/db              # 数据库数据存储位置
        - ./mongo/configdb:/data/configdb
      image: mongo:4.2
      container_name: mongo
      restart: always
      command: --auth
      environment:
        MONGO_INITDB_ROOT_USERNAME: dbadmin
        MONGO_INITDB_ROOT_PASSWORD: dbadmin
        MONGO_INITDB_DATABASE: mydb
        MONGO_USERNAME: dbuser
        MONGO_PASSWORD: dbuser
  mongo-express:
      image: mongo-express
      ports:
        - "80:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
        ME_CONFIG_MONGODB_ADMINPASSWORD: dbadmin
        ME_CONFIG_MONGODB_SERVER: mongo
      restart: always
      links:
        - mongo     